services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener_app
    ports:
      - 5433:5432
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
  web:
    image: goshorty
    restart: always
    build: .
    environment:
      GOSHORTY_LISTENADDR: 0.0.0.0:8080
      GOSHORTY_REQUESTSPERMINUTE: 60
      GOSHORTY_CONNINFO: postgresql://postgres:postgres@db:5432/url_shortener_app?sslmode=disable
    ports:
      - 8081:8080
    links:
      - db